# Generated by Django 4.2.5 on 2025-04-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_code", models.IntegerField()),
                ("crime_code", models.IntegerField()),
                ("year", models.IntegerField()),
                ("population", models.FloatField()),
            ],
        ),
    ]
